module.exports = {
  filter: '.',
  indent: '  ',
  dependencyTypes: [
    'dev',
    'prod',
    'overrides',
    'pnpmOverrides',
    'resolutions',
    'local'
  ],
  semverGroups: [],
  semverRange: '^',
  sortAz: [
    'contributors',
    'dependencies',
    'devDependencies',
    'keywords',
    'peerDependencies',
    'resolutions',
    'scripts'
  ],
  sortFirst: [
    'name',
    'serviceName',
    'version',
    'private',
    'license',
    'description',
    'author',
    'contributors',
    'funding',
    'homepage',
    'repository',
    'source',
    'publishConfig',
    'engines',
    'packageManager',
    'bugs',
    'type',
    'main',
    'types',
    'files',
    'workspaces',
    'module',
    'exports',
    'typings',
    'typesVersions',
    'files',
    'sideEffects',
    'scripts',
    'browserslist',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'resolutions',
    'keywords'
  ],
  source: [],
  versionGroups: []
}
