# .github/workflows/release.yml
name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONFIG_REGISTRY: https://npm.pkg.github.com/
      NPM_CONFIG_REGISTRY: https://registry.npmjs.org
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.8.32
        with:
          install-command: yarn --frozen-lockfile --ignore-scripts

      - name: Semantic Release
        id: semantic
        run: |
          yarn multi-semantic-release --sequential-init
        env:
          # Tokens for semantic release
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          # Github token for publishing package to Github Package Registry
          GITHUB_NPM_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: ${{ env.GITHUB_CONFIG_REGISTRY }}
          # NPM token for publishing package to NPM Public Package Registry
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: ${{ env.NPM_CONFIG_REGISTRY }}
