# .github/workflows/release.yml
name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.8.7

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Semantic Release
        id: semantic
        run: |
          yarn multi-semantic-release --sequential-init
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Push updates to branch for major version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
